name: apps
on: [push]
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: echo "Hello world"
      - run: npm i -g tldr
      - run: tldr cat
    
  
